[custom]
clash_rule_base=https://raw.githubusercontent.com/yleaway/Clash-Rules/refs/heads/main/Router/base.yaml

; 开启 Geo 数据库自动更新（Mihomo/Meta 内核支持）
geodata_loader=mem-conservative
geo_auto_update=true
geo_update_interval=24
; 设置 Loyalsoldier 的下载源
geoip_url=https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
geosite_url=https://fastly.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat

; ================= 分流规则 (Ruleset) =================
; 1. 强制 DNS 服务器 IP 归位
ruleset=🎯 Direct,[]IP-CIDR,223.5.5.5/32,no-resolve
ruleset=🎯 Direct,[]IP-CIDR,119.29.29.29/32,no-resolve
ruleset=🎯 Direct,[]IP-CIDR,1.12.12.12/32,no-resolve
ruleset=🎯 Direct,[]IP-CIDR,180.184.1.1/32,no-resolve

; 2. 基础分流规则 
ruleset=🎯 Direct,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
ruleset=🔔 GoogleFCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list
ruleset=⛔ AdBlock,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.list
ruleset=⛔ AdBlock,[]GEOSITE,CATEGORY-ADS-ALL
ruleset=📺 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🏰 DisneyPlus,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🤖 OpenAI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=📷 Instagram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.list
ruleset=🟢 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Spotify/Spotify.list
ruleset=▶️ Youtube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=💬 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🔍 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🤖 Copilot,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list
ruleset=📥 OneDrive,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=🎮 Games,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=⏲️ Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=🧱 GFW,[]GEOSITE,GFW,no-resolve
ruleset=🎯 Direct,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/UnionPay/UnionPay.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
ruleset=🎯 Direct,[]GEOSITE,CN,no-resolve
ruleset=🎯 Direct,[]GEOIP,CN,no-resolve
ruleset=🐟 Final,[]FINAL

; ================= 策略组 (Proxy Group) =================
custom_proxy_group=🧱 GFW`select`.*`[]DIRECT
custom_proxy_group=♻️ Auto`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=💬 Telegram`select`.*
custom_proxy_group=▶️ Youtube`select`.*
custom_proxy_group=📺 Netflix`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)
custom_proxy_group=🏰 DisneyPlus`select`(DSN|迪士尼|解锁|Disney|DISNEY|Media)
custom_proxy_group=📷 Instagram`select`.*
custom_proxy_group=🎵 TikTok`select`.*
custom_proxy_group=🟢 Spotify`select`.*
custom_proxy_group=🤖 OpenAI`select`.*`[]DIRECT
custom_proxy_group=🤖 Copilot`select`.*`[]DIRECT
custom_proxy_group=🔍 Google`select`.*`[]DIRECT
custom_proxy_group=⏲️ Speedtest`select`[]DIRECT`.*
custom_proxy_group=🔔 GoogleFCM`select`[]DIRECT`.*
custom_proxy_group=📥 OneDrive`select`[]DIRECT`.*
custom_proxy_group=🪟 Microsoft`select`[]DIRECT`.*
custom_proxy_group=🍎 Apple`select`[]DIRECT`.*
custom_proxy_group=🎮 Games`select`[]DIRECT`.*
custom_proxy_group=🎯 Direct`select`[]DIRECT`.*
custom_proxy_group=⛔ AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 Final`select`.*`[]DIRECT

; ================= 核心开关 =================
enable_rule_generator=true
overwrite_original_rules=true
enable_dns=true
overwrite_dns=true
